/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class vuelo extends javax.swing.JPanel {

    /**
     * Creates new form vuelo
     */
    public vuelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opc_Origen = new javax.swing.JComboBox<>();
        opc_Destino = new javax.swing.JComboBox<>();
        Calendario_S = new com.toedter.calendar.JDateChooser();
        opc_Cantidad_S = new javax.swing.JComboBox<>();
        opc_Can_nino_S = new javax.swing.JComboBox<>();
        b_ida1 = new javax.swing.JToggleButton();
        O_F_V = new javax.swing.JComboBox<>();
        D_F_V = new javax.swing.JComboBox<>();
        F_I_V = new com.toedter.calendar.JDateChooser();
        F_R_V = new com.toedter.calendar.JDateChooser();
        C_A_V = new javax.swing.JComboBox<>();
        C_N_V = new javax.swing.JComboBox<>();
        B_iva_y_vuelta = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opc_Origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "Guayaquil", "Cuenca", " " }));
        opc_Origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_OrigenActionPerformed(evt);
            }
        });
        add(opc_Origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 30));

        opc_Destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Roma", "Chicago", "NewYour", "Pekin", " " }));
        opc_Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_DestinoActionPerformed(evt);
            }
        });
        add(opc_Destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 30));
        add(Calendario_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 30));

        opc_Cantidad_S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "otro", " " }));
        opc_Cantidad_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_Cantidad_SActionPerformed(evt);
            }
        });
        add(opc_Cantidad_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        opc_Can_nino_S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "otro" }));
        opc_Can_nino_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_Can_nino_SActionPerformed(evt);
            }
        });
        add(opc_Can_nino_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        b_ida1.setText("Solo-Ida");
        b_ida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ida1ActionPerformed(evt);
            }
        });
        add(b_ida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 80));

        O_F_V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUITO", "GUAYAQUIL", "CUENCA" }));
        O_F_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_F_VActionPerformed(evt);
            }
        });
        add(O_F_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 150, 30));

        D_F_V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MADRID", "MURCIA", "NEW YOUR", "CHICAGO" }));
        D_F_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_F_VActionPerformed(evt);
            }
        });
        add(D_F_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 160, 30));
        add(F_I_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 200, 40));
        add(F_R_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 170, 40));

        C_A_V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        C_A_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_A_VActionPerformed(evt);
            }
        });
        add(C_A_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 70, 30));

        C_N_V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        C_N_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_N_VActionPerformed(evt);
            }
        });
        add(C_N_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 70, 30));

        B_iva_y_vuelta.setText("Ida y Vuelta");
        B_iva_y_vuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_iva_y_vueltaActionPerformed(evt);
            }
        });
        add(B_iva_y_vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 170, 90));

        jLabel1.setText("Origin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 134, 70, 20));

        jLabel2.setText("Destino");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        jLabel3.setText("Fecha de ida");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel4.setText("Origin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel5.setText("Destino");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel6.setText("Adulto");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 80, 30));

        jLabel7.setText("Niño");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoSample_ByTailorBrands (1).jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 110));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pie.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 640, 110));

        jLabel10.setText("Fecha ida");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel11.setText("Fecha regreso");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/j.jpg"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 240, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void opc_OrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_OrigenActionPerformed
        /*String mensaje;
        mensaje=opc_Origen.getSelectedItem().toString();
        caja de texto.setText(el string)
        O_S.setText(mensaje);

        */

    }//GEN-LAST:event_opc_OrigenActionPerformed

    private void opc_DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_DestinoActionPerformed

        /*String mensaje;
        mensaje=opc_Destino.getSelectedItem().toString();

        D_S.setText(mensaje);
        */

    }//GEN-LAST:event_opc_DestinoActionPerformed

    private void opc_Cantidad_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_Cantidad_SActionPerformed
        /*
        String mensaje;
        mensaje=opc_Cantidad_S.getSelectedItem().toString();

        C_S.setText(mensaje);*/
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_Cantidad_SActionPerformed

    private void opc_Can_nino_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_Can_nino_SActionPerformed

        /*
        String mensaje;
        mensaje=opc_Can_nino_S.getSelectedItem().toString();

        N_S.setText(mensaje);
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_Can_nino_SActionPerformed

    private void b_ida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ida1ActionPerformed

        try {

            PreparedStatement ps;
            Conectar conle= new Conectar();

            String Origen=opc_Origen.getSelectedItem().toString();
            String Destino=opc_Destino.getSelectedItem().toString();

            int Adu_can=Integer.parseInt(opc_Cantidad_S.getSelectedItem().toString());
            int Nin_can=Integer.parseInt(opc_Can_nino_S.getSelectedItem().toString());

            Date fechatxt = null;

            try {

                java.util.Date fechaIni=Calendario_S.getDate();
                //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                fechatxt = new java.sql.Date(fechaIni.getTime());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Eroror en fecha dia/mes/año");
                Logger.getLogger(vuelo.class.getName()).log(Level.SEVERE, null, e);
            }

            ps=conle.getConex().prepareStatement("insert into Reserva_Solo(Origen_solo,Destino_solo,fecha_vuelo_solo,Adulto_Cantidad_solo,Nino_Catidad_solo) values(?,?,?,?,?)");

            ps.setString(1, Origen);
            ps.setString(2, Destino);
            ps.setDate(3,fechatxt);
            ps.setInt(4, Adu_can);
            ps.setInt(5, Nin_can);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "registro guardado");

        } catch (SQLException ex) {
            Logger.getLogger(vuelo.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(null, "error en el ingreso");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vuelo.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Seleccon p1=new Seleccion();
       
    }//GEN-LAST:event_b_ida1ActionPerformed

    private void O_F_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_F_VActionPerformed
        /*
        String mensaje;
        mensaje=O_F_V.getSelectedItem().toString();

        O_V.setText(mensaje);
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_O_F_VActionPerformed

    private void D_F_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_F_VActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_D_F_VActionPerformed

    private void C_A_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_A_VActionPerformed

    }//GEN-LAST:event_C_A_VActionPerformed

    private void C_N_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_N_VActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_C_N_VActionPerformed

    private void B_iva_y_vueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_iva_y_vueltaActionPerformed
        try {

            PreparedStatement ps;
            //cargar driver
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //conexion con base de datos
            String url = "jdbc:sqlserver://localhost:1433;databaseName=modelos";
            Connection Con = DriverManager.getConnection(url, "sa", "123456");

            String Origen=O_F_V.getSelectedItem().toString();
            String Destino=D_F_V.getSelectedItem().toString();

            int Adu_can=Integer.parseInt(C_A_V.getSelectedItem().toString());
            int Nin_can=Integer.parseInt(C_N_V.getSelectedItem().toString());

            Date fechatxt = null;
            try {

                java.util.Date fechaIni=F_I_V.getDate();

                fechatxt = new java.sql.Date(fechaIni.getTime());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Eroror en fecha dia/mes/año");
                Logger.getLogger(vuelo.class.getName()).log(Level.SEVERE, null, e);
            }

            Date fechatxt2 = null;
            try {
                java.util.Date fechaR=F_R_V.getDate();

                fechatxt2= new java.sql.Date(fechaR.getTime());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Eroror en fecha dia/mes/año");
                Logger.getLogger(vuelo.class.getName()).log(Level.SEVERE, null, e);
            }

            ps = Con.prepareStatement("insert into Reserva_Varios(Origen_varios,Destino_varios,fecha_vuelo_ida_varios,fecha_vuelo_regreso_varios,Adulto_Cantidad_varios,Nino_Catidad_varios) values(?,?,?,?,?,?)");

            ps.setString(1, Origen);
            ps.setString(2, Destino);
            ps.setDate(3, fechatxt);
            ps.setDate(4, fechatxt2);
            ps.setInt(5, Adu_can);
            ps.setInt(6, Nin_can);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "registro guardado");

        } catch (ClassNotFoundException e) {
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error en el ingreso");
            e.printStackTrace();
        }

    }//GEN-LAST:event_B_iva_y_vueltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton B_iva_y_vuelta;
    private javax.swing.JComboBox<String> C_A_V;
    private javax.swing.JComboBox<String> C_N_V;
    private com.toedter.calendar.JDateChooser Calendario_S;
    private javax.swing.JComboBox<String> D_F_V;
    private com.toedter.calendar.JDateChooser F_I_V;
    private com.toedter.calendar.JDateChooser F_R_V;
    private javax.swing.JComboBox<String> O_F_V;
    private javax.swing.JToggleButton b_ida1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> opc_Can_nino_S;
    private javax.swing.JComboBox<String> opc_Cantidad_S;
    private javax.swing.JComboBox<String> opc_Destino;
    private javax.swing.JComboBox<String> opc_Origen;
    // End of variables declaration//GEN-END:variables
}
